CREATE DATABASE Projeto_SP_Med_Group;
GO
USE Projeto_SP_Med_Group;
GO

--> CRIANDO TABELAS TIPOUSUARIO
CREATE TABLE tipoUsuario(
	idTipousuario TINYINT PRIMARY KEY IDENTITY,
	tituloTipoUsuario VARCHAR (100)UNIQUE NOT NULL
);
GO

--> CRIANDO TABELA USUARIO
CREATE TABLE usuario(
	idUsuario SMALLINT PRIMARY KEY IDENTITY,
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES tipoUsuario (idTipoUsuario),
	email VARCHAR(256)NOT NULL UNIQUE,
	senha VARCHAR(15)NOT NULL
);
GO

--> CRIANDO TABELA PACIENTE
DROP TABLE paciente
CREATE TABLE paciente(
	idPaciente SMALLINT PRIMARY KEY IDENTITY,
	idUsuario SMALLINT FOREIGN KEY REFERENCES usuario(idUsuario),
	nomePaciente VARCHAR(100)NOT NULL,
	dataNascimento DATE NOT NULL,
	telefone VARCHAR(20) ,
	RG CHAR(10)NOT NULL UNIQUE,
	CPF CHAR(11),
	endereco VARCHAR(200)NOT NULL
);
GO

--> CRIANDO TABELA ESPECIALIZACAO
CREATE TABLE especializacao(
	idEspecializacao SMALLINT PRIMARY KEY IDENTITY,
	tipoEspecializacao VARCHAR(100) NOT NULL UNIQUE
);
GO
--> CRIANDO TABELA CLINICA
CREATE TABLE clinica (
	idClinica SMALLINT PRIMARY KEY IDENTITY,
	nomeFantasia VARCHAR(100)NOT NULL,
	CNPJ CHAR(18)NOT NULL UNIQUE,
	razaoSocial VARCHAR(100)NOT NULL UNIQUE,
	endereco VARCHAR(200)NOT NULL UNIQUE
);
GO


--> CRIANDO TABELA MEDICO
CREATE TABLE medico(
	idMedico SMALLINT PRIMARY KEY IDENTITY,
	idUsuario SMALLINT FOREIGN KEY REFERENCES usuario(idUsuario),
	idEspecializacao SMALLINT FOREIGN KEY REFERENCES especializacao(idEspecializacao),
	idClinica SMALLINT FOREIGN KEY REFERENCES clinica(idClinica),
	nomeMedico VARCHAR(100)NOT NULL,
	CRM VARCHAR (15)NOT NULL UNIQUE
);
GO


--> CRIANDO TABELA SITUACAO

CREATE TABLE situacao(
	idSituacao SMALLINT PRIMARY KEY IDENTITY,
	situacao VARCHAR(100)
);
GO


--> CRIANDO TABELA CONSULTA
drop table consulta
CREATE TABLE consulta(
	idConsulta SMALLINT PRIMARY KEY IDENTITY,
	idPaciente SMALLINT FOREIGN KEY REFERENCES paciente(idPaciente),
	idMedico SMALLINT FOREIGN KEY REFERENCES medico(idMedico),
	idSituacao SMALLINT FOREIGN KEY REFERENCES situacao(idSituacao)DEFAULT (3),
	dataConsulta DATETIME,
	descricao VARCHAR(70)
);
GO

--> CRIANDO TABELA DE IMAGEMUSUARIO
CREATE TABLE imagemUsuario(     
id INT PRIMARY KEY IDENTITY(1,1),     
idUsuario SMALLINT NOT NULL UNIQUE FOREIGN KEY REFERENCES usuario(idUsuario),
binario VARBINARY(MAX) NOT NULL,    
mimeType VARCHAR(30) NOT NULL,    
nomeArquivo VARCHAR(250) NOT NULL,     
data_inclusao DATETIME DEFAULT GETDATE() NULL 
); 
GO


--> Criou um evento para que a idade do usuário seja calculada todos os dias
ALTER TABLE paciente
ADD idadePaciente TINYINT


CREATE PROCEDURE SP_IDADE_PACIENTE
AS 
BEGIN

UPDATE paciente SET idadePaciente = DATEDIFF(YEAR,dataNascimento,GETDATE())

END 

EXEC SP_IDADE_PACIENTE

SELECT * FROM paciente